In [1]:
from keras.preprocessing import image
import numpy as np
import os
from pathlib import Path
import pandas as pd

In [2]:
data = pd.read_csv('train.csv')

In [3]:
import matplotlib.pyplot as plt
img_data = []
labels = []
for index, row in data.iterrows():
    img = image.load_img('Images/'+row['ImageId'], target_size = (32, 32))
    img_data.append(img)
    labels.append(row['NameOfPokemon'])
# print(img_data)
# print(labels)
# p = Path("Images")
# fold = p.glob("*.jpg")
# img_data = []
# labels = []
# for imge in fold:
#     label = str(imge).split('\\')[-1]
#     img = image.load_img(imge, target_size = (32, 32))
#     img_data.append(img)
#     labels.append(label)

c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\PIL\Image.py:970: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


In [4]:
""" convert this into numpy array"""
img_data = np.array(img_data, dtype = 'float32') / 255.0
labels = np.array(labels)
# print(img_data.shape, labels.shape)

In [5]:
#random

In [6]:
img_data = img_data.reshape(img_data.shape[0], -1)

In [7]:
from sklearn import svm

In [8]:
#print(labels)
#kernel='linear'

In [9]:
svmm = svm.SVC(kernel='poly')
svmm.fit(img_data, labels)

SVC(kernel='poly')

In [10]:
svmm.score(img_data, labels)

0.9802631578947368

In [11]:
test_data = pd.read_csv('test.csv')


In [12]:
timg_data = []
ref = []
for index, row in test_data.iterrows():
    img = image.load_img('Images/'+row['ImageId'], target_size = (32, 32))
    ref.append(row['ImageId'])
    timg_data.append(img)

In [13]:
# print(timg_data)

In [14]:
timg_data = np.array(timg_data)

In [15]:
timg_data = timg_data.reshape(timg_data.shape[0],-1)
print(timg_data)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [217 217 217 ... 217 217 217]
 [ 48 128 107 ... 172 207  89]
 [109 109 109 ...  15  15  15]]


In [16]:
pred = svmm.predict(timg_data)

In [19]:
df = pd.DataFrame(data=pred, columns = ['NameOfPokemon'])
df.insert(0, "ImageId", ref, True)
df.to_csv('goa_svm.csv', index = False)